### ISSUE TITLE
Cant find the Decryption key

### ISSUE THREAD

**Issue by Flameshocker** [Lebedev21/Finnish-Army-Simulator-Save-Editor#2]
Cant find the Decryption key in dnSpy 

![image](https://user-images.githubusercontent.com/25096682/214916344-77dca170-3a90-41b8-9bb8-09f47c97d642.png)
![image](https://user-images.githubusercontent.com/25096682/214916563-99e660ad-34d0-431a-aa1e-1d78026b5a62.png)

**Comment by Lebedev21** [comment]
Yeah sorry I used the old mono dlls. I will check where the key is in the il2cpp version.
Stay tuned. I'll update the wiki.
